import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/components/Navbar/Navbar";
import Body from "../components/components/Body/Body";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Twittr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.png" />
      </Head>

      <Navbar />
      <Body />
    </div>
  );
}
